### PR TITLE
STREAMS-2203 - Add a caution note to do a backup before upgrade

### PR DESCRIPTION
**Pull request by rbissey-axway**
Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

Add a caution note to do a backup before upgrade.
https://deploy-preview-116--streams-open-docs.netlify.app/docs/install/upgrade/

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

### CODE REVIEW

**Comment by cremond** [comment]
Hello @rbissey-axway , it looks all good to me! However I think for this one there must also be a review by our PO (@guillaumelamirand ) before we submit this to Andrea.

**Review by guillaumelamirand — APPROVED** [review]

**Comment by guillaumelamirand** [comment]
@andreamussap Could you please review this PR ?

**Comment by andreamussap** [comment]
> @andreamussap Could you please review this PR ?

@guillaumelamirand please have a look at my changes and let me know if it's ok to merge. Thanks

**Comment by guillaumelamirand** [comment]
> > @andreamussap Could you please review this PR ?
> 
> @guillaumelamirand please have a look at my changes and let me know if it's ok to merge. Thanks

All good.

**Pull request merged**
