### PR TITLE
STREAMS-2132 Update nginx version

### PR DESCRIPTION
**Pull request by guillaumelamirand**
Thank you for your contribution to the Axway Streams documentation.

## Describe the changes

https://deploy-preview-109--streams-open-docs.netlify.app/docs/architecture/#nginx

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

### CODE REVIEW

**Comment by dominiquemongelli** [comment]
Could you update zookeeper version from 3.7.0-debian-10-r95 to 3.7.0-debian-10-r98 ? Thanks

**Comment by guillaumelamirand** [comment]
> 3.7.0-debian-10-r98

Done

**Review by dominiquemongelli — APPROVED** [review]

**Comment by guillaumelamirand** [comment]
@andreamussap Don't know if I already sent you a request or not. Could you please review this PR? Thanks

**Comment by andreamussap** [comment]
> @andreamussap Don't know if I already sent you a request or not. Could you please review this PR? Thanks

@guillaumelamirand I've made small changes. Please let me know if I can merge the PR ?

**Comment by guillaumelamirand** [comment]
> > @andreamussap Don't know if I already sent you a request or not. Could you please review this PR? Thanks
> 
> @guillaumelamirand I've made small changes. Please let me know if I can merge the PR ?

Ok for me. You can merge. Thank you

**Pull request merged**
